/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MedicationsRouteImport } from './routes/medications'
import { Route as MedicalRecordsRouteImport } from './routes/medical-records'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EmergencyQrRouteImport } from './routes/emergency-qr'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as AiAssistantRouteImport } from './routes/ai-assistant'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmergencyUserIdRouteImport } from './routes/emergency/$userId'

const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicationsRoute = MedicationsRouteImport.update({
  id: '/medications',
  path: '/medications',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicalRecordsRoute = MedicalRecordsRouteImport.update({
  id: '/medical-records',
  path: '/medical-records',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyQrRoute = EmergencyQrRouteImport.update({
  id: '/emergency-qr',
  path: '/emergency-qr',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAssistantRoute = AiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyUserIdRoute = EmergencyUserIdRouteImport.update({
  id: '/emergency/$userId',
  path: '/emergency/$userId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/appointments': typeof AppointmentsRoute
  '/dashboard': typeof DashboardRoute
  '/emergency-qr': typeof EmergencyQrRoute
  '/login': typeof LoginRoute
  '/medical-records': typeof MedicalRecordsRoute
  '/medications': typeof MedicationsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/timeline': typeof TimelineRoute
  '/emergency/$userId': typeof EmergencyUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/appointments': typeof AppointmentsRoute
  '/dashboard': typeof DashboardRoute
  '/emergency-qr': typeof EmergencyQrRoute
  '/login': typeof LoginRoute
  '/medical-records': typeof MedicalRecordsRoute
  '/medications': typeof MedicationsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/timeline': typeof TimelineRoute
  '/emergency/$userId': typeof EmergencyUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/appointments': typeof AppointmentsRoute
  '/dashboard': typeof DashboardRoute
  '/emergency-qr': typeof EmergencyQrRoute
  '/login': typeof LoginRoute
  '/medical-records': typeof MedicalRecordsRoute
  '/medications': typeof MedicationsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/timeline': typeof TimelineRoute
  '/emergency/$userId': typeof EmergencyUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-assistant'
    | '/appointments'
    | '/dashboard'
    | '/emergency-qr'
    | '/login'
    | '/medical-records'
    | '/medications'
    | '/profile'
    | '/register'
    | '/timeline'
    | '/emergency/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-assistant'
    | '/appointments'
    | '/dashboard'
    | '/emergency-qr'
    | '/login'
    | '/medical-records'
    | '/medications'
    | '/profile'
    | '/register'
    | '/timeline'
    | '/emergency/$userId'
  id:
    | '__root__'
    | '/'
    | '/ai-assistant'
    | '/appointments'
    | '/dashboard'
    | '/emergency-qr'
    | '/login'
    | '/medical-records'
    | '/medications'
    | '/profile'
    | '/register'
    | '/timeline'
    | '/emergency/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiAssistantRoute: typeof AiAssistantRoute
  AppointmentsRoute: typeof AppointmentsRoute
  DashboardRoute: typeof DashboardRoute
  EmergencyQrRoute: typeof EmergencyQrRoute
  LoginRoute: typeof LoginRoute
  MedicalRecordsRoute: typeof MedicalRecordsRoute
  MedicationsRoute: typeof MedicationsRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  TimelineRoute: typeof TimelineRoute
  EmergencyUserIdRoute: typeof EmergencyUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medications': {
      id: '/medications'
      path: '/medications'
      fullPath: '/medications'
      preLoaderRoute: typeof MedicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medical-records': {
      id: '/medical-records'
      path: '/medical-records'
      fullPath: '/medical-records'
      preLoaderRoute: typeof MedicalRecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency-qr': {
      id: '/emergency-qr'
      path: '/emergency-qr'
      fullPath: '/emergency-qr'
      preLoaderRoute: typeof EmergencyQrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-assistant': {
      id: '/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency/$userId': {
      id: '/emergency/$userId'
      path: '/emergency/$userId'
      fullPath: '/emergency/$userId'
      preLoaderRoute: typeof EmergencyUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiAssistantRoute: AiAssistantRoute,
  AppointmentsRoute: AppointmentsRoute,
  DashboardRoute: DashboardRoute,
  EmergencyQrRoute: EmergencyQrRoute,
  LoginRoute: LoginRoute,
  MedicalRecordsRoute: MedicalRecordsRoute,
  MedicationsRoute: MedicationsRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  TimelineRoute: TimelineRoute,
  EmergencyUserIdRoute: EmergencyUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
